// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvFNc1IDmBdDdM1kIq-Rc1CWExi638aw',
    appId: '1:569704069874:web:7ad4fcfc3691fcba4b6e6b',
    messagingSenderId: '569704069874',
    projectId: 'd-chat-cc26f',
    authDomain: 'd-chat-cc26f.firebaseapp.com',
    storageBucket: 'd-chat-cc26f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYMPm4ULqFXnX4rTjxz88jVpJxEzKbq0',
    appId: '1:569704069874:android:5e5b4201906846a64b6e6b',
    messagingSenderId: '569704069874',
    projectId: 'd-chat-cc26f',
    storageBucket: 'd-chat-cc26f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFN7Sea28v_XrJm2qxmtwIn-yBzGRf4Pg',
    appId: '1:569704069874:ios:d810523c9dc10cb24b6e6b',
    messagingSenderId: '569704069874',
    projectId: 'd-chat-cc26f',
    storageBucket: 'd-chat-cc26f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFN7Sea28v_XrJm2qxmtwIn-yBzGRf4Pg',
    appId: '1:569704069874:ios:d810523c9dc10cb24b6e6b',
    messagingSenderId: '569704069874',
    projectId: 'd-chat-cc26f',
    storageBucket: 'd-chat-cc26f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSvFNc1IDmBdDdM1kIq-Rc1CWExi638aw',
    appId: '1:569704069874:web:f13059939a356fc34b6e6b',
    messagingSenderId: '569704069874',
    projectId: 'd-chat-cc26f',
    authDomain: 'd-chat-cc26f.firebaseapp.com',
    storageBucket: 'd-chat-cc26f.appspot.com',
  );

}